### ISSUE TITLE
Depend on `backports` package

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/backports.tarfile-feedstock#1]
The [`backports` package]( https://github.com/conda-forge/backports-feedstock ) makes sure that the top-level package is `import`able and doesn't create clobber errors with other `backports.*` packages that need (and create) the top-level `backports` package. To ensure `backports.tarfile` works with other `backports.*`, would suggest adding `backports` as a `host` and `run` dependency of `backports.tarfile`

**Comment by carlodri** [comment]
Thanks a lot for this insight @jakirkham, I had no idea of this! I've prepared PR #2, if you can kindly review it to make sure I understood correctly, and then I will merge, thanks!
